server:
  port: 8085

spring:
  datasource:
    url: ${RESULT_DB_URL:jdbc:mysql://localhost:3306/certifypro_result?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

resilience4j:
  circuitbreaker:
    instances:
      candidate-service:
        base-config: default
      exam-service:
        base-config: default
      question-service:
        base-config: default
      certificate-service:
        base-config: default
      notification-service:
        base-config: default
